- optimizer_scripts/tools/helper.py
- optimizer_scripts/tools/other.py
* Support auto_pad shape inference for Conv.
* Fix bug in upsample shape inference.
* Fix bug in attribute processing.
> Support auto_pad shape inference for Conv.

- optimizer_scripts/tools/replacing.py
Hi,
I got problem when replace squeeze op to flatten op,
here is a solution,
please check it.
Thanks!
> check value_info exists before remove it

- optimizer_scripts/tensorflow2onnx.py
1. Support tf2onnx V1.5.x and V1.6.x
2. Using tf2onnx.optimizer pre-optimize ONNX
3. Reformat coding style from `Tab Size 2, Indent Size 2` to `Tab Size 4, Indent Size 4`
4. Logging optimize information
> Support tf2onnx V1.5.x and V1.6.x, Using tf2onnx.optimizer pre optimize onnx

- tflite-onnx/README.md
Hi,
revise readme for tflite2onnx
Thanks!
> revise readme

- tflite-onnx/onnx_tflite/core_layers.py
HI,
I found sometimes the ReshapeOption() could return empty result and crash.
So I add some rule to fix it.
Please check it,
Thanks!
> fix issue: op.BuiltinOptions is none in OP:reshape

- optimizer_scripts/tools/fusing.py
Hi,
I found "fuse_mul_and_add_into_bn" not support two dimension case,
and here is the solution
Thanks!
> support 2 dim's add-mul fusing into bn

- optimizer_scripts/onnx2onnx.py
- optimizer_scripts/tools/other.py
It is only activated when `--add-bn` is set.
> Add function which add bn before activation nodes.

- optimizer_scripts/editor.py
- optimizer_scripts/tools/other.py
Hi,
Here is the feature branch merge request,
I add new feature for add shift-conv in editor.py,
for the hardware optimized pre-process.
Thanks
> tool for adding shift conv for add_norm

- tflite-onnx/onnx_tflite/base_layer.py
- tflite-onnx/onnx_tflite/core_layers.py
Hi,
I fix a crash issue in case of the empty bias node in FC layer
thanks!
> tflite2onnx: fix bug while FC layer without bias

- optimizer_scripts/tools/replacing.py
- tflite-onnx/README.md
Hi,
here is some update,
1. Fix a bug while replacing mul to bn in case of InceptionResnetV2,
which is only one mul value.
2. Update tflite2onnx readme for dependency lib
thanks.
> onnx2onnx bug fix and document update

- keras-onnx/onnx_keras/merg_layers.py
- optimizer_scripts/pytorch_exported_onnx_preprocess.py
Fix keras-onnx concat axis.
Copy and rename `pytorch2onnx.py` to `pytorch_exported_onnx_preprocess.py` to avoid misunderstanding of the script usage.
> Add pytorch preprocess script.

- caffe-onnx/onnx_caffe/aact_layers.py
Fix caffe-onnx incorrect PRelu weight broadcast.
> Fix caffe prelu

- optimizer_scripts/tools/constant_folding.py
When all inputs for BN are constants, do constant folding.
> Add BN constant folding.

- optimizer_scripts/tools/removing_transpose.py
fix bug in case of gemm at model top in fuse_Transpose_into_Gemm_weight
> fix crash issue while gemm at top

- optimizer_scripts/onnx1.3to1.4.py
MXNet exported onnx are from opset9, with 1-D PRelu weight.
> Support mxnet exported onnx.

- keras-onnx/onnx_keras/core_layers.py
Hi,
I got a wrong result issue in case of fused softmax node in conv,
here is the solution.
please check it.
thanks.
> fix keras 4d softmax wrong result issue

- optimizer_scripts/onnx2onnx.py
- optimizer_scripts/tools/combo.py
- optimizer_scripts/tools/constant_folding.py
- optimizer_scripts/tools/helper.py
- optimizer_scripts/tools/other.py
- optimizer_scripts/tools/torch_pattern.py
Hi,
I fix some constant folding issue in case of onnx from pytorch.
It happen when pytorch user use nn.UpsamplingBilinear2d
please check it.
Thanks!
> fix constant folding issue: Resize from torch UpsamplingBilinear2d

- optimizer_scripts/tools/helper.py
Hi,
still need a little revise.
thanks.
> change version info to global type

- optimizer_scripts/tools/replacing.py
Now it will check 0 or -1 in shapes while replacing Shape with Constant.
> Fix bug caused by 0 in shapes.

- keras-onnx/onnx_keras/conv_layers.py
- optimizer_scripts/tools/other.py
> Fix keras ConvTranspose Conversion

- optimizer_scripts/tools/constant_folding.py
Hi,
I got concat constant folding data type issue,
here is my solution.
thanks.
> fix concat constant folding data type issue

- optimizer_scripts/tools/combo.py
- optimizer_scripts/tools/modhelper.py
- optimizer_scripts/tools/other.py
Hi,
I got a pytorch constant folding issue due to onnx.shape_inferece could not work with some Resize operator case.
So I calculate for it mannully.
thanks.
> calcualte inference shape mannully for op:Resize

- optimizer_scripts/onnx2onnx.py
- optimizer_scripts/tools/special.py
It serves the same purpose as the rgba2yynn.py under keras-onnx.
> Add rgba to yynn node.

- optimizer_scripts/tools/other.py
Hi,
I modified the epsilon value of generated nop_bn, 
make it smaller, to make sure it could not influence the inference result.
thanks!
> revise epsilon value of nop_bn

- optimizer_scripts/tensorflow2onnx.py
- optimizer_scripts/tools/replacing.py
Hi,
Recently tf2onnx can't pass onnx.utils.polish_model if we set output opset > 8.
Here I make tf2onnx compatible with onnx.utils.polish_model.
thanks.
> make tf2onnx opset 9 compatible with onnx.utils.polish_model

- keras-onnx/onnx_keras/aact_layers.py
- keras-onnx/onnx_keras/conv_layers.py
- keras-onnx/onnx_keras/frontend.py
- keras-onnx/onnx_keras/helper.py
- tflite-onnx/onnx_tflite/aact_layers.py
- tflite-onnx/onnx_tflite/conv_layers.py
- tflite-onnx/onnx_tflite/core_layers.py
- tflite-onnx/onnx_tflite/tflite2onnx.py
- tflite-onnx/onnx_tflite/utils.py
Hi,
here is update:
caffe convertor tested under opset11
keras convertor upgraded to opset11
tflite convertor upgraded to opset11
the old branch just broken in accident,
here is the new one
thanks!
> Onnx opset11 rebased

- README.md
- keras-onnx/README.md
- keras-onnx/onnx_keras/aact_layers.py
- keras-onnx/onnx_keras/conv_layers.py
- keras-onnx/onnx_keras/frontend.py
- keras-onnx/onnx_keras/helper.py
- optimizer_scripts/editor.py
- optimizer_scripts/onnx1_4to1_6.py
- optimizer_scripts/onnx2onnx.py
- optimizer_scripts/pytorch2onnx.py
- optimizer_scripts/pytorch_exported_onnx_preprocess.py
- optimizer_scripts/tensorflow2onnx.py
- optimizer_scripts/tools/combo.py
- optimizer_scripts/tools/common_pattern.py
- optimizer_scripts/tools/constant_folding.py
- optimizer_scripts/tools/helper.py
- optimizer_scripts/tools/other.py
- optimizer_scripts/tools/removing_transpose.py
- optimizer_scripts/tools/replacing.py
- optimizer_scripts/tools/special.py
- tflite-onnx/README.md
- tflite-onnx/onnx_tflite/aact_layers.py
- tflite-onnx/onnx_tflite/conv_layers.py
- tflite-onnx/onnx_tflite/core_layers.py
- tflite-onnx/onnx_tflite/tflite2onnx.py
- tflite-onnx/onnx_tflite/utils.py
Update the opset 11 converters into the master branch.
> Update opset 11 into master

- optimizer_scripts/tools/combo.py
- optimizer_scripts/tools/replacing.py
Replace Add with BN
Remove bn replacing dimension limit.
> Replace add with bn

- optimizer_scripts/tools/common_pattern.py
- optimizer_scripts/tools/constant_folding.py
- optimizer_scripts/tools/helper.py
Fix node not found in common_pattern
> Fix value not found in unsqueeze_constant_folding

- caffe-onnx/onnx_caffe/__init__.py
- caffe-onnx/onnx_caffe/base_layer.py
- caffe-onnx/onnx_caffe/frontend.py
- caffe-onnx/onnx_caffe/helper.py
- caffe-onnx/onnx_caffe/norm_layers.py
- keras-onnx/onnx_keras/base_layer.py
- keras-onnx/onnx_keras/frontend.py
- keras-onnx/onnx_keras/helper.py
- optimizer_scripts/tensorflow2onnx.py
- tflite-onnx/onnx_tflite/aact_layers.py
- tflite-onnx/onnx_tflite/conv_layers.py
- tflite-onnx/onnx_tflite/core_layers.py
- tflite-onnx/onnx_tflite/merg_layers.py
- tflite-onnx/onnx_tflite/pool_layers.py
- tflite-onnx/onnx_tflite/tflite2onnx.py
- tflite-onnx/onnx_tflite/tflite_utils.py
No new progress. Skip tensorflow for now.
> Prepare for toolchain python api

- tflite-onnx/onnx_tflite/aact_layers.py
- tflite-onnx/onnx_tflite/conv_layers.py
- tflite-onnx/onnx_tflite/core_layers.py
- tflite-onnx/onnx_tflite/merg_layers.py
- tflite-onnx/onnx_tflite/pool_layers.py
- tflite-onnx/onnx_tflite/tflite2onnx.py
- tflite-onnx/onnx_tflite/tflite_utils.py
- tflite-onnx/onnx_tflite/tree_structure.py
Reverts kneron/ONNX_Convertor#69
> Revert "TFLite quant models essentials "

- tflite-onnx/onnx_tflite/aact_layers.py
- tflite-onnx/onnx_tflite/conv_layers.py
- tflite-onnx/onnx_tflite/core_layers.py
- tflite-onnx/onnx_tflite/merg_layers.py
- tflite-onnx/onnx_tflite/pool_layers.py
- tflite-onnx/onnx_tflite/tflite2onnx.py
- tflite-onnx/onnx_tflite/tflite_utils.py
- tflite-onnx/onnx_tflite/tree_structure.py
Reverts kneron/ONNX_Convertor#71
> Revert "Revert "TFLite quant models essentials ""

- optimizer_scripts/onnx2onnx.py
- optimizer_scripts/tools/special.py
Optimize MatMul with option `--op-matmul` for hardware.
> Revisit MatMul

- optimizer_scripts/tools/combo.py
- optimizer_scripts/tools/other.py
- optimizer_scripts/tools/replacing.py
> Fix Split node replacement.

- optimizer_scripts/editor.py
- optimizer_scripts/tools/other.py
allow adding input preproc BN into none-3-channel-input model
> allow adding input preproc BN into none-3-channel-input model

- optimizer_scripts/onnx2onnx.py
Update python doc according to new param.
> Update doc of onnx2onnx flow.

- optimizer_scripts/pytorch_exported_onnx_preprocess.py
- optimizer_scripts/tools/combo.py
- optimizer_scripts/tools/constant_folding.py
- optimizer_scripts/tools/eliminating.py
- optimizer_scripts/tools/fusing.py
- optimizer_scripts/tools/helper.py
- optimizer_scripts/tools/other.py
- optimizer_scripts/tools/replacing.py
Fix bugs found while processing models from paddle model zoo.
> WIP: Fix bugs in paddle models

- optimizer_scripts/tools/special.py
Fix value not found issue with opt-matmul flag.
> Fix bug in opt matmul.

- optimizer_scripts/tools/special.py
> Update matmul optimization generated node name.

- optimizer_scripts/tools/combo.py
- optimizer_scripts/tools/eliminating.py
- optimizer_scripts/tools/special.py
Support split bn which batch sizes are not 1.
> Eliminate do-nothing Cast nodes.

- optimizer_scripts/batch_size_change.py
- optimizer_scripts/tools/combo.py
- optimizer_scripts/tools/common_pattern.py
- optimizer_scripts/tools/constant_folding.py
- optimizer_scripts/tools/helper.py
- optimizer_scripts/tools/replacing.py
Fix polish model cannot process initializer correctly.
Fix Resize after input may cause shape not found.
Fix opset 12 Slice constant folding not done.
Optimize some debug outputs.
> Fix bugs found while processing tflite exported model.

- optimizer_scripts/tools/fusing.py
- optimizer_scripts/verify/onnx_vs_onnx.py
- optimizer_scripts/verify/onnx_vs_onnx_opt.py
- optimizer_scripts/verify/tflite_vs_onnx.py
Fix onnx_vs_onnx import issue.
> Fix double free in the fusing slice into conv function.

- optimizer_scripts/batch_size_change.py
- optimizer_scripts/loop_model_process.py
- optimizer_scripts/onnx1_3to1_4.py
- optimizer_scripts/tools/combo.py
- optimizer_scripts/tools/common_pattern.py
- optimizer_scripts/tools/constant_folding.py
- optimizer_scripts/tools/defusing.py
- optimizer_scripts/tools/eliminating.py
- optimizer_scripts/tools/fusing.py
Improve Mul Add fusion to support transpose cases.
Use safer value_info remove function for part of code.
> Defuse Div into Reciprocal and Mul

- optimizer_scripts/tools/constant_folding.py
Add work around for float64 Cast constant folding.
Fix scalar reciprocal constant folding.
> Add Pow constant folding.

- optimizer_scripts/tools/constant_folding.py
- optimizer_scripts/tools/other.py
- optimizer_scripts/tools/replacing.py
support extra constant folding nodes and fix some bugs
> Cs hot fix

- optimizer_scripts/tools/common_pattern.py
- optimizer_scripts/tools/constant_folding.py
- optimizer_scripts/tools/defusing.py
- optimizer_scripts/tools/helper.py
- optimizer_scripts/tools/removing_transpose.py
- optimizer_scripts/tools/replacing.py
- optimizer_scripts/verify/onnx_vs_onnx.py
Fix einsum defusing function. 
Add type check in tools/common_pattern.py.
Add type definition for zero length numpy array in numpy_to_constant function.
> Einsum fix
